---
networks:
  base-birthday-buddy-network:
    driver: bridge

services:
  # ---------------------------------------------------------------------
  # | Nginx Web Server
  # ---------------------------------------------------------------------
  proxy:
    container_name: ${COMPOSE_PROJECT_NAME}_proxy
    build:
      context: ../../../
      dockerfile: .${PROXY_PROJECT_PATH}/Dockerfile.dev
      args:
        - PROXY_PROJECT_PATH=${PROXY_PROJECT_PATH}
    ports:
      - "3000:80"
    restart: unless-stopped
    networks:
      - base-birthday-buddy-network
    depends_on:
      - react-ui-service
      - nodejs-api-service

  # ---------------------------------------------------------------------
  # | React.js UI-CSR Service                                           |
  # ---------------------------------------------------------------------
  react-ui-service:
    build:
      context: ../../../
      dockerfile: .${APP_PROJECT_PATH}/Dockerfile.dev
      args:
        - APP_PROJECT_PATH=${APP_PROJECT_PATH}
        - PROTOCOL=${PROTOCOL}
        - DOMAIN=${DOMAIN}
        - PORT=${UI_SERVICE_PORT}
    environment:
      - SERVICE_NAME=react-ui-service
      - PROTOCOL=${PROTOCOL}
      - DOMAIN=${DOMAIN}
      - PORT=${UI_SERVICE_PORT}
    volumes:
      - /usr/src/app/node_modules # Avoids overwriting node_modules with local volume
      - ../../../${APP_PROJECT_PATH}:/usr/src/app
    networks:
      - base-birthday-buddy-network

  # ---------------------------------------------------------------------
  # | Node.js API Service                                               |
  # ---------------------------------------------------------------------
  nodejs-api-service:
    build:
      context: ../../../
      dockerfile: .${API_PROJECT_PATH}/Dockerfile.dev
      args:
        - API_PROJECT_PATH=${API_PROJECT_PATH}
        - PORT=${API_SERVICE_PORT}
        - SERVICE_NAME=nodejs-api-service
    env_file:
      - ../../configuration/env/.${PROJECT_NAME}.compose.env
    environment:
      - SERVICE_NAME=nodejs-api-service
      - PROTOCOL=${PROTOCOL}
      - DOMAIN=${DOMAIN}
      - PORT=${API_SERVICE_PORT}
    volumes:
      - /usr/src/app/node_modules # Avoids overwriting node_modules with local volume
      - ../../../${API_PROJECT_PATH}:/usr/src/app
    networks:
      - base-birthday-buddy-network
