---
networks:
  base-nodejs-network:
    driver: bridge

volumes:
  dev-db-data:

services:
  # ---------------------------------------------------------------------
  # | Node.js API Service                                               | 
  # ---------------------------------------------------------------------
  nodejs-api-service:
    build:
      context: ../../../
      dockerfile: .${API_PROJECT_PATH}/Dockerfile.dev
      args:
        - API_PROJECT_PATH=${API_PROJECT_PATH}
        - NODE_PORT=${NODE_PORT}
    ports:
      - "3000:${NODE_PORT}"
    env_file:
      - ../../configuration/env/.${PROJECT_NAME}.compose.env
    volumes:
      - /usr/src/app/node_modules # Avoids overwriting node_modules with local volume
      - ../../../${API_PROJECT_PATH}:/usr/src/app
    networks:
      - base-nodejs-network
