# Generated by Django 3.2.25 on 2025-02-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_root',
            field=models.BooleanField(default=False),
        ),
    ]
