@base_url = http://localhost:3000

### list all habitats
GET {{base_url}}/api/habitats
Content-Type: application/json

### get habitat by id
GET {{base_url}}/api/habitats/1
Content-Type: application/json

### create habitat
POST {{base_url}}/api/habitats
Content-Type: application/json

{
    "name": "ice-desert",
    "climate": "wet",
    "temperature": -100
}

### update habitat
PUT {{base_url}}/api/habitats/1
Content-Type: application/json

{
    "name": "desert",
    "climate": "dry",
    "temperature": 125
}

### delete habitat
DELETE {{base_url}}/api/habitats/4
Content-Type: application/json
