FROM node:22.14.0-bullseye-slim
LABEL maintainer="paulserban.eu"

ARG CMS_PROJECT_PATH
ARG PORT
ARG NODE_ENV=development

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY .${CMS_PROJECT_PATH}/package.json /usr/src/app/
# Installing libvips-dev for sharp Compatability
RUN apt-get update && apt-get install libvips-dev -y

ENV PORT=${PORT}
ENV NODE_ENV=${NODE_ENV}

RUN yarn config set network-timeout 600000 -g && yarn install

COPY .${CMS_PROJECT_PATH}/ /usr/src/app/

RUN yarn build

# Command to run when the container is ready
# Separate arguments as separate values in the array
CMD [ "yarn", "run", "develop"]
