INFRA_ORCHESTRATION_SCRIPTS_DOCKER_DIR := ./infrastructure/orchestration/docker

compose-up:
	@bash $(INFRA_ORCHESTRATION_SCRIPTS_DOCKER_DIR)/base.elegant-use-context-w-use-reducer-online-shop.docker-compose.bash --phase=up --app-name=elegant-use-context-w-use-reducer-online-shop

compose-down:
	@bash $(INFRA_ORCHESTRATION_SCRIPTS_DOCKER_DIR)/base.elegant-use-context-w-use-reducer-online-shop.docker-compose.bash --phase=down --app-name=elegant-use-context-w-use-reducer-online-shop

compose-down-clean:
	@bash $(INFRA_ORCHESTRATION_SCRIPTS_DOCKER_DIR)/base.elegant-use-context-w-use-reducer-online-shop.docker-compose.bash --phase=down-clean --app-name=elegant-use-context-w-use-reducer-online-shop





compose-up-prod:
	@bash $(INFRA_ORCHESTRATION_SCRIPTS_DOCKER_DIR)/base.elegant-use-context-w-use-reducer-online-shop.docker-compose.bash --phase=up-prod --app-name=elegant-use-context-w-use-reducer-online-shop

compose-down-prod:
	@bash $(INFRA_ORCHESTRATION_SCRIPTS_DOCKER_DIR)/base.elegant-use-context-w-use-reducer-online-shop.docker-compose.bash --phase=down-prod --app-name=elegant-use-context-w-use-reducer-online-shop

compose-down-clean-prod:
	@bash $(INFRA_ORCHESTRATION_SCRIPTS_DOCKER_DIR)/base.elegant-use-context-w-use-reducer-online-shop.docker-compose.bash --phase=down-clean-prod --app-name=elegant-use-context-w-use-reducer-online-shop
