@base_url = http://localhost:8000

###
GET {{base_url}}/api/hello-viewset
Content-Type: application/json

###
POST {{base_url}}/api/hello-viewset/
Content-Type: application/json

{
  "name": "John"
}

###
PUT {{base_url}}/api/hello-viewset/1/
Content-Type: application/json

###
PATCH {{base_url}}/api/hello-viewset/1/
Content-Type: application/json

{
  "name": "John"
}

###
DELETE {{base_url}}/api/hello-viewset/1/
Content-Type: application/json
