### List all messages
GET http://localhost:3000/messages

### Create a new message
POST http://localhost:3000/messages
content-type: application/json

{
  "content": "Hello, NestJS!"
}

### Get a message by ID
GET http://localhost:3000/messages/11