FROM nginx:1.22.1

# Install required packages for WebDAV
RUN apt-get update && apt-get install -y nginx-extras && apt-get clean

RUN ln -sf /dev/stdout /var/log/nginx/access.log \
	&& ln -sf /dev/stderr /var/log/nginx/error.log

# Create a directory for uploads
RUN mkdir -p /usr/share/nginx/html/uploads

COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

RUN chown -R www-data:www-data /usr/share/nginx/html/uploads
RUN chmod -R 755 /usr/share/nginx/html/uploads

