FROM node:22.14.0-bullseye-slim

ARG APP_PROJECT_PATH
ARG PORT

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

ENV PORT=$PORT

COPY .${APP_PROJECT_PATH}/package.json /usr/src/app/

EXPOSE $PORT

RUN yarn install

COPY .${APP_PROJECT_PATH}/ /usr/src/app/

CMD [ "yarn", "run", "develop"]