INFRA_ORCHESTRATION_SCRIPTS_DOCKER_DIR := ./infrastructure/orchestration/docker

color-button-compose-up:
	@bash $(INFRA_ORCHESTRATION_SCRIPTS_DOCKER_DIR)/base.color-button.docker-compose.bash --phase=up --app-name=color-button

color-button-compose-down:
	@bash $(INFRA_ORCHESTRATION_SCRIPTS_DOCKER_DIR)/base.color-button.docker-compose.bash --phase=down --app-name=color-button

color-button-compose-down-clean:
	@bash $(INFRA_ORCHESTRATION_SCRIPTS_DOCKER_DIR)/base.color-button.docker-compose.bash --phase=down-clean --app-name=color-button





color-button-compose-up-prod:
	@bash $(INFRA_ORCHESTRATION_SCRIPTS_DOCKER_DIR)/base.color-button.docker-compose.bash --phase=up-prod --app-name=color-button

color-button-compose-down-prod:
	@bash $(INFRA_ORCHESTRATION_SCRIPTS_DOCKER_DIR)/base.color-button.docker-compose.bash --phase=down-prod --app-name=color-button

color-button-compose-down-clean-prod:
	@bash $(INFRA_ORCHESTRATION_SCRIPTS_DOCKER_DIR)/base.color-button.docker-compose.bash --phase=down-clean-prod --app-name=color-button
