INFRA_ORCHESTRATION_SCRIPTS_DOCKER_DIR := ./infrastructure/orchestration/docker

shopping-cart-usereducer-compose-up:
	@bash $(INFRA_ORCHESTRATION_SCRIPTS_DOCKER_DIR)/base.shopping-cart-usereducer.docker-compose.bash --phase=up --app-name=shopping-cart-usereducer

shopping-cart-usereducer-compose-down:
	@bash $(INFRA_ORCHESTRATION_SCRIPTS_DOCKER_DIR)/base.shopping-cart-usereducer.docker-compose.bash --phase=down --app-name=shopping-cart-usereducer

shopping-cart-usereducer-compose-down-clean:
	@bash $(INFRA_ORCHESTRATION_SCRIPTS_DOCKER_DIR)/base.shopping-cart-usereducer.docker-compose.bash --phase=down-clean --app-name=shopping-cart-usereducer





shopping-cart-usereducer-compose-up-prod:
	@bash $(INFRA_ORCHESTRATION_SCRIPTS_DOCKER_DIR)/base.shopping-cart-usereducer.docker-compose.bash --phase=up-prod --app-name=shopping-cart-usereducer

shopping-cart-usereducer-compose-down-prod:
	@bash $(INFRA_ORCHESTRATION_SCRIPTS_DOCKER_DIR)/base.shopping-cart-usereducer.docker-compose.bash --phase=down-prod --app-name=shopping-cart-usereducer

shopping-cart-usereducer-compose-down-clean-prod:
	@bash $(INFRA_ORCHESTRATION_SCRIPTS_DOCKER_DIR)/base.shopping-cart-usereducer.docker-compose.bash --phase=down-clean-prod --app-name=shopping-cart-usereducer
