FROM nginx:1.22.1

ARG PROXY_PROJECT_PATH

RUN apt-get update && apt-get clean

RUN ln -sf /dev/stdout /var/log/nginx/access.log \
	&& ln -sf /dev/stderr /var/log/nginx/error.log

RUN echo ${PROXY_PROJECT_PATH}

COPY .${PROXY_PROJECT_PATH}/nginx/default.conf /etc/nginx/conf.d/default.conf
