---
networks:
  base-nextjs-network:
    driver: bridge

services:
  # ---------------------------------------------------------------------
  # | Nginx Web Server
  # ---------------------------------------------------------------------
  proxy:
    container_name: ${COMPOSE_PROJECT_NAME}_proxy
    build:
      context: ../../../
      dockerfile: .${PROXY_PROJECT_PATH}/Dockerfile.dev
      args:
        - PROXY_PROJECT_PATH=${PROXY_PROJECT_PATH}
    ports:
      - "3000:80"
    restart: unless-stopped
    networks:
      - base-nextjs-network

  # ---------------------------------------------------------------------
  # | Node.js SSR Service                                               |
  # ---------------------------------------------------------------------
  nextjs-ssr-service:
    build:
      context: ../../../
      dockerfile: .${SSR_PROJECT_PATH}/Dockerfile.dev
      args:
        - SSR_PROJECT_PATH=${SSR_PROJECT_PATH}
        - PORT=${PORT}
    env_file:
      - ../../configuration/env/.${PROJECT_NAME}.compose.env
    volumes:
      - /usr/src/app/node_modules # Avoids overwriting node_modules with local volume
      - ../../../${SSR_PROJECT_PATH}:/usr/src/app
    networks:
      - base-nextjs-network
