---
networks:
  base-nextjs-network:
    driver: bridge

services:
  # ---------------------------------------------------------------------
  # | Nginx Web Server
  # ---------------------------------------------------------------------
  proxy:
    container_name: ${COMPOSE_PROJECT_NAME}_proxy
    build:
      context: ../../../
      dockerfile: .${PROXY_PROJECT_PATH}/Dockerfile.dev
      args:
        - PROXY_PROJECT_PATH=${PROXY_PROJECT_PATH}
    ports:
      - "3000:80"
    restart: unless-stopped
    networks:
      - base-nextjs-network

  # ---------------------------------------------------------------------
  # | Node.js SSR Service                                               |
  # ---------------------------------------------------------------------
  nextjs-ssr-service:
    build:
      context: ../../../
      dockerfile: .${SSR_PROJECT_PATH}/Dockerfile.dev
      args:
        - SSR_PROJECT_PATH=${SSR_PROJECT_PATH}
        - PORT=${PORT}
    env_file:
      - ../../configuration/env/.${PROJECT_NAME}.compose.env
    environment:
      - SERVICE_NAME=nextjs-ssr-service
    volumes:
      - /usr/src/app/node_modules # Avoids overwriting node_modules with local volume
      - ../../../${SSR_PROJECT_PATH}:/usr/src/app
    networks:
      - base-nextjs-network

  # ---------------------------------------------------------------------
  # | AWS LocalStack Infrastructure                                          |
  # ---------------------------------------------------------------------
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566" # LocalStack Gateway
      - "4510-4559:4510-4559" # Additional service ports
    environment:
      - SERVICES=lambda,apigateway,s3,iam
      - DEBUG=1
      - PERSISTENCE=1
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=localstack
      - AWS_SECRET_ACCESS_KEY=localstack
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock" # Required for running Lambdas in containers
      - "../../configuration/scripts/localstack/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh" # Auto-create resources
    networks:
      - base-nextjs-network