FROM node:22.14.0-bullseye-slim

ARG SSR_PROJECT_PATH

ARG PROTOCOL
ARG HOSTNAME
ARG PORT

ARG API_URL
ARG APP_URL
ARG CMS_URL

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

ENV PORT=$PORT

ENV NEXT_PUBLIC_PROTOCOL=$PROTOCOL
ENV NEXT_PUBLIC_HOSTNAME=$HOSTNAME
ENV NEXT_PUBLIC_PORT=$PORT

ENV NEXT_PUBLIC_APP_URL=$APP_URL
ENV NEXT_PUBLIC_API_URL=$API_URL

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY .${SSR_PROJECT_PATH}/package.json .${SSR_PROJECT_PATH}/yarn.lock /usr/src/app/

EXPOSE $PORT

RUN yarn install

# Bundle app source
COPY .${SSR_PROJECT_PATH}/ /usr/src/app/

CMD [ "yarn", "run", "develop"]