FROM python:3.12.9-alpine
LABEL maintainer="paulserban.eu"

ENV PYTHONUNBUFFERED 1

ARG API_PROJECT_PATH

COPY .${API_PROJECT_PATH}/requirements.txt /tmp/requirements.txt
COPY .${API_PROJECT_PATH}/requirements.dev.txt /tmp/requirements.dev.txt
COPY .${API_PROJECT_PATH}/app /app
WORKDIR /app

EXPOSE 8000

RUN apk add --update --no-cache postgresql-client && \
    apk add --update --no-cache --virtual .tmp-build-deps \
    postgresql-dev build-base musl-dev

ARG DEV=false

RUN python -m venv /py && \
    /py/bin/pip install --upgrade pip && \
    /py/bin/pip install -r /tmp/requirements.txt

RUN if [ "$DEV" = "true" ]; then \
        /py/bin/pip install -r /tmp/requirements.dev.txt; \
    fi
RUN rm -rf /tmp
RUN apk del .tmp-build-deps

RUN adduser \
        --disabled-password \
        --no-create-home \
        django-user

ENV PATH="/py/bin:$PATH"

USER django-user