FROM postgres:13-alpine
LABEL maintainer="paulserban.eu"

ARG PROJECT_NAME
ARG POSTGRES_PASSWORD

ENV PGPASSWORD=${POSTGRES_PASSWORD}

# Copy the seed.sql script into the container
COPY ./database/seeds/${PROJECT_NAME}-db/seed.sql /docker-entrypoint-initdb.d/seed.sql

# Set the entrypoint to run the seed script
ENTRYPOINT ["sh", "-c", "psql -h $DB_HOST -U $POSTGRES_USER -d $POSTGRES_DB -f /docker-entrypoint-initdb.d/seed.sql"]