FROM nginx:1.26.3

ARG SERVER_PROJECT_PATH

RUN apt-get update && apt-get clean

RUN ln -sf /dev/stdout /var/log/nginx/access.log \
	&& ln -sf /dev/stderr /var/log/nginx/error.log

RUN echo ${SERVER_PROJECT_PATH}

COPY .${SERVER_PROJECT_PATH}/nginx/default.conf /etc/nginx/conf.d/default.conf

COPY .${SERVER_PROJECT_PATH}/src /usr/share/nginx/html