FROM nginx:1.26.3

ARG PROXY_PROJECT_PATH

RUN apt-get update && apt-get clean

RUN ln -sf /dev/stdout /var/log/nginx/access.log \
	&& ln -sf /dev/stderr /var/log/nginx/error.log

COPY .${PROXY_PROJECT_PATH}/nginx/dev.conf /etc/nginx/conf.d/default.conf
