---
networks:
  prod-reactjs-network:
    driver: bridge

services:
  # ---------------------------------------------------------------------
  # | React.js UI-CSR Service                                           | 
  # ---------------------------------------------------------------------
  react-ui-service:
    build:
      context: ../../../
      dockerfile: .${APP_PROJECT_PATH}/Dockerfile.prod
      args:
        - APP_PROJECT_PATH=${APP_PROJECT_PATH}
        - PORT=${PORT}
    ports:
      - "3080:80"
    env_file:
      - ../../configuration/env/.${PROJECT_NAME}.compose.env
    volumes:
      - /usr/src/app/node_modules # Avoids overwriting node_modules with local volume
      - ../../../${APP_PROJECT_PATH}:/usr/src/app
    networks:
      - prod-reactjs-network
